name: Run Tài Xỉu Dự Đoán

on:
  schedule:
    - cron: "*/5 * * * *"  # Chạy mỗi 5 phút
  workflow_dispatch:       # Cho phép chạy thủ công

jobs:
  run-taixiu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v3

      - name: Cài Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cài thư viện
        run: |
          pip install -r requirements.txt

      - name: Chạy script Tài Xỉu
        run: python taixiu.py
